name: Grading Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  grade-scripting:
    name: Scripting Grading
    uses: salvamiguel/grading-workflows/.github/workflows/scripting_grading.yaml@v1.0.1
